Autoload protobuf-mode so it works with Emacs 23
The protobuf-mode file doesn't load correctly on Emacs startup with
Emacs 23.  You get the following error:

  error: `c-lang-defconst` must be used in a file

You can get around this error by autoloading the Emacs mode when it's
first used.